### ISSUE TITLE
clash-lib-1.8.1 failed to build with ghc-9.8.4 Stackage Nightly

### ISSUE THREAD

**Issue by juhp** [clash-lang/clash-compiler#2852]
```
       /home/curators/work/unpack-dir/unpacked/clash-lib-1.8.1-03ec2cb411fe7ac811914edffea21995ffd0d5c5b6898264fc548c766d146ecb/src/
Clash/Core/Type.hs:516:20: error: [GHC-83865]                                                                                       
           • Couldn't match type ‘GHC.Word.Word64’ with ‘Int’                                                                       
             Expected: Clash.Unique.Unique                                                                                          
               Actual: GHC.Word.Word64                                                                                              
           • In the second argument of ‘(==)’, namely                                                                               
               ‘getKey typeNatAddTyFamNameKey’                                                                                      
             In the expression: nameUniq tc == getKey typeNatAddTyFamNameKey                                                        
             In a stmt of a pattern guard for                                                                                       
                            an equation for ‘reduceTypeFamily’:                                                                     
               nameUniq tc == getKey typeNatAddTyFamNameKey                                                                         
           |                                                                                                                        
       516 |   | nameUniq tc == getKey typeNatAddTyFamNameKey                                                                       
           |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                       
                                                                                                                                    
       /home/curators/work/unpack-dir/unpacked/clash-lib-1.8.1-03ec2cb411fe7ac811914edffea21995ffd0d5c5b6898264fc548c766d146ecb/src/
Clash/Core/Type.hs:521:20: error: [GHC-83865]                                                                                       
           • Couldn't match type ‘GHC.Word.Word64’ with ‘Int’                                                                       
             Expected: Clash.Unique.Unique                                                                                          
               Actual: GHC.Word.Word64                                                                                              
           • In the second argument of ‘(==)’, namely
               ‘getKey typeNatMulTyFamNameKey’
             In the expression: nameUniq tc == getKey typeNatMulTyFamNameKey
             In a stmt of a pattern guard for
                            an equation for ‘reduceTypeFamily’:
               nameUniq tc == getKey typeNatMulTyFamNameKey
           |
       521 |   | nameUniq tc == getKey typeNatMulTyFamNameKey
           |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        
       /home/curators/work/unpack-dir/unpacked/clash-lib-1.8.1-03ec2cb411fe7ac811914edffea21995ffd0d5c5b6898264fc548c766d146ecb/src/
Clash/Core/Type.hs:526:20: error: [GHC-83865]
           • Couldn't match type ‘GHC.Word.Word64’ with ‘Int’
             Expected: Clash.Unique.Unique
               Actual: GHC.Word.Word64
           • In the second argument of ‘(==)’, namely
               ‘getKey typeNatExpTyFamNameKey’
             In the expression: nameUniq tc == getKey typeNatExpTyFamNameKey
             In a stmt of a pattern guard for
                            an equation for ‘reduceTypeFamily’:
                            an equation for ‘reduceTypeFamily’:                                                01:50:14 [313/937727]
               nameUniq tc == getKey typeNatExpTyFamNameKey                                                                         
           |
       526 |   | nameUniq tc == getKey typeNatExpTyFamNameKey
           |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        
       /home/curators/work/unpack-dir/unpacked/clash-lib-1.8.1-03ec2cb411fe7ac811914edffea21995ffd0d5c5b6898264fc548c766d146ecb/src/
Clash/Core/Type.hs:531:20: error: [GHC-83865]
           • Couldn't match type ‘GHC.Word.Word64’ with ‘Int’
             Expected: Clash.Unique.Unique
               Actual: GHC.Word.Word64
           • In the second argument of ‘(==)’, namely
               ‘getKey typeNatSubTyFamNameKey’
             In the expression: nameUniq tc == getKey typeNatSubTyFamNameKey
             In a stmt of a pattern guard for
                            an equation for ‘reduceTypeFamily’:
               nameUniq tc == getKey typeNatSubTyFamNameKey
           |
       531 |   | nameUniq tc == getKey typeNatSubTyFamNameKey
           |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        
       /home/curators/work/unpack-dir/unpacked/clash-lib-1.8.1-03ec2cb411fe7ac811914edffea21995ffd0d5c5b6898264fc548c766d146ecb/src/
Clash/Core/Type.hs:552:20: error: [GHC-83865]
           • Couldn't match type ‘GHC.Word.Word64’ with ‘Int’
             Expected: Clash.Unique.Unique
               Actual: GHC.Word.Word64
           • In the second argument of ‘(==)’, namely
               ‘getKey typeNatCmpTyFamNameKey’
             In the expression: nameUniq tc == getKey typeNatCmpTyFamNameKey
             In a stmt of a pattern guard for
                            an equation for ‘reduceTypeFamily’:
               nameUniq tc == getKey typeNatCmpTyFamNameKey
           |
       552 |   | nameUniq tc == getKey typeNatCmpTyFamNameKey -- "GHC.TypeNats.CmpNat"
           |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        
       /home/curators/work/unpack-dir/unpacked/clash-lib-1.8.1-03ec2cb411fe7ac811914edffea21995ffd0d5c5b6898264fc548c766d146ecb/src/
Clash/Core/Type.hs:557:45: error: [GHC-83865]
           • Couldn't match type ‘GHC.Word.Word64’ with ‘Int’
             Expected: Clash.Unique.Unique
               Actual: GHC.Word.Word64
           • In the third argument of ‘Name’, namely
               ‘(getKey ordLTDataConKey)’
             In the expression:
               Name User "GHC.Types.LT" (getKey ordLTDataConKey) wiredInSrcSpan
             In a case alternative:
                 LT
                   -> Name User "GHC.Types.LT" (getKey ordLTDataConKey) wiredInSrcSpan
           |
       557 |             LT -> Name User "GHC.Types.LT" (getKey ordLTDataConKey) wiredInSrcSpan
           |                                             ^^^^^^^^^^^^^^^^^^^^^^
        
       /home/curators/work/unpack-dir/unpacked/clash-lib-1.8.1-03ec2cb411fe7ac811914edffea21995ffd0d5c5b6898264fc548c766d146ecb/src/
Clash/Core/Type.hs:558:45: error: [GHC-83865]
           • Couldn't match type ‘GHC.Word.Word64’ with ‘Int’
             Expected: Clash.Unique.Unique
               Actual: GHC.Word.Word64
           • In the third argument of ‘Name’, namely
               ‘(getKey ordEQDataConKey)’
             In the expression:
               Name User "GHC.Types.EQ" (getKey ordEQDataConKey) wiredInSrcSpan
             In a case alternative:
                 EQ
                   -> Name User "GHC.Types.EQ" (getKey ordEQDataConKey) wiredInSrcSpan
           |
       558 |             EQ -> Name User "GHC.Types.EQ" (getKey ordEQDataConKey) wiredInSrcSpan
           |                                             ^^^^^^^^^^^^^^^^^^^^^^
        
       /home/curators/work/unpack-dir/unpacked/clash-lib-1.8.1-03ec2cb411fe7ac811914edffea21995ffd0d5c5b6898264fc548c766d146ecb/src/
Clash/Core/Type.hs:559:45: error: [GHC-83865]
           • Couldn't match type ‘GHC.Word.Word64’ with ‘Int’
             Expected: Clash.Unique.Unique
               Actual: GHC.Word.Word64
           • In the third argument of ‘Name’, namely
               ‘(getKey ordGTDataConKey)’
             In the expression:
               Name User "GHC.Types.GT" (getKey ordGTDataConKey) wiredInSrcSpan
             In a case alternative:
                 GT
                   -> Name User "GHC.Types.GT" (getKey ordGTDataConKey) wiredInSrcSpan
           |
       559 |             GT -> Name User "GHC.Types.GT" (getKey ordGTDataConKey) wiredInSrcSpan
           |                                             ^^^^^^^^^^^^^^^^^^^^^^
        
       /home/curators/work/unpack-dir/unpacked/clash-lib-1.8.1-03ec2cb411fe7ac811914edffea21995ffd0d5c5b6898264fc548c766d146ecb/src/
Clash/Core/Type.hs:562:20: error: [GHC-83865]
           • Couldn't match type ‘GHC.Word.Word64’ with ‘Int’
             Expected: Clash.Unique.Unique
               Actual: GHC.Word.Word64
           • In the second argument of ‘(==)’, namely
               ‘getKey typeSymbolCmpTyFamNameKey’
             In the expression: nameUniq tc == getKey typeSymbolCmpTyFamNameKey
             In a stmt of a pattern guard for
                            an equation for ‘reduceTypeFamily’:
               nameUniq tc == getKey typeSymbolCmpTyFamNameKey
           |
       562 |   | nameUniq tc == getKey typeSymbolCmpTyFamNameKey -- "GHC.TypeNats.CmpSymbol"
           |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        
       /home/curators/work/unpack-dir/unpacked/clash-lib-1.8.1-03ec2cb411fe7ac811914edffea21995ffd0d5c5b6898264fc548c766d146ecb/src/
Clash/Core/Type.hs:567:45: error: [GHC-83865]
           • Couldn't match type ‘GHC.Word.Word64’ with ‘Int’
             Expected: Clash.Unique.Unique
               Actual: GHC.Word.Word64
           • In the third argument of ‘Name’, namely
               ‘(getKey ordLTDataConKey)’
             In the expression:
               Name User "GHC.Types.LT" (getKey ordLTDataConKey) wiredInSrcSpan
             In a case alternative:
                 LT
                   -> Name User "GHC.Types.LT" (getKey ordLTDataConKey) wiredInSrcSpan
           |
       567 |             LT -> Name User "GHC.Types.LT" (getKey ordLTDataConKey) wiredInSrcSpan
           |                                             ^^^^^^^^^^^^^^^^^^^^^^
        
       /home/curators/work/unpack-dir/unpacked/clash-lib-1.8.1-03ec2cb411fe7ac811914edffea21995ffd0d5c5b6898264fc548c766d146ecb/src/
Clash/Core/Type.hs:568:45: error: [GHC-83865]
           • Couldn't match type ‘GHC.Word.Word64’ with ‘Int’
             Expected: Clash.Unique.Unique
               Actual: GHC.Word.Word64
           • In the third argument of ‘Name’, namely
               ‘(getKey ordEQDataConKey)’
             In the expression:
               Name User "GHC.Types.EQ" (getKey ordEQDataConKey) wiredInSrcSpan
             In a case alternative:
                 EQ
                   -> Name User "GHC.Types.EQ" (getKey ordEQDataConKey) wiredInSrcSpan
           |
       568 |             EQ -> Name User "GHC.Types.EQ" (getKey ordEQDataConKey) wiredInSrcSpan
           |                                             ^^^^^^^^^^^^^^^^^^^^^^
        
       /home/curators/work/unpack-dir/unpacked/clash-lib-1.8.1-03ec2cb411fe7ac811914edffea21995ffd0d5c5b6898264fc548c766d146ecb/src/
Clash/Core/Type.hs:569:45: error: [GHC-83865]
           • Couldn't match type ‘GHC.Word.Word64’ with ‘Int’
             Expected: Clash.Unique.Unique
               Actual: GHC.Word.Word64
           • In the third argument of ‘Name’, namely
               ‘(getKey ordGTDataConKey)’
             In the expression:
               Name User "GHC.Types.GT" (getKey ordGTDataConKey) wiredInSrcSpan
             In a case alternative:
                 GT
                   -> Name User "GHC.Types.GT" (getKey ordGTDataConKey) wiredInSrcSpan
           |
       569 |             GT -> Name User "GHC.Types.GT" (getKey ordGTDataConKey) wiredInSrcSpan
           |                                             ^^^^^^^^^^^^^^^^^^^^^^
        
       /home/curators/work/unpack-dir/unpacked/clash-lib-1.8.1-03ec2cb411fe7ac811914edffea21995ffd0d5c5b6898264fc548c766d146ecb/src/
Clash/Core/Type.hs:573:20: error: [GHC-83865]
           • Couldn't match type ‘GHC.Word.Word64’ with ‘Int’
             Expected: Clash.Unique.Unique
               Actual: GHC.Word.Word64
           • In the second argument of ‘(==)’, namely
               ‘getKey typeCharCmpTyFamNameKey’
             In the expression: nameUniq tc == getKey typeCharCmpTyFamNameKey
             In a stmt of a pattern guard for
                            an equation for ‘reduceTypeFamily’:
               nameUniq tc == getKey typeCharCmpTyFamNameKey
           |
       573 |   | nameUniq tc == getKey typeCharCmpTyFamNameKey -- "GHC.TypeNats.CmpSymbol"
           |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        
       /home/curators/work/unpack-dir/unpacked/clash-lib-1.8.1-03ec2cb411fe7ac811914edffea21995ffd0d5c5b6898264fc548c766d146ecb/src/
Clash/Core/Type.hs:578:42: error: [GHC-83865]
           • Couldn't match type ‘GHC.Word.Word64’ with ‘Int’
             Expected: Clash.Unique.Unique
               Actual: GHC.Word.Word64
           • In the third argument of ‘Name’, namely
               ‘(getKey ordLTDataConKey)’
             In the expression:
               Name User (showt 'LT) (getKey ordLTDataConKey) wiredInSrcSpan
             In a case alternative:
                 LT -> Name User (showt 'LT) (getKey ordLTDataConKey) wiredInSrcSpan
           |
       578 |             LT -> Name User (showt 'LT) (getKey ordLTDataConKey) wiredInSrcSpan
           |                                          ^^^^^^^^^^^^^^^^^^^^^^
        
       /home/curators/work/unpack-dir/unpacked/clash-lib-1.8.1-03ec2cb411fe7ac811914edffea21995ffd0d5c5b6898264fc548c766d146ecb/src/
Clash/Core/Type.hs:579:42: error: [GHC-83865]
           • Couldn't match type ‘GHC.Word.Word64’ with ‘Int’
             Expected: Clash.Unique.Unique
               Actual: GHC.Word.Word64
           • In the third argument of ‘Name’, namely
               ‘(getKey ordEQDataConKey)’
             In the expression:
               Name User (showt 'EQ) (getKey ordEQDataConKey) wiredInSrcSpan
             In a case alternative:
                 EQ -> Name User (showt 'EQ) (getKey ordEQDataConKey) wiredInSrcSpan
           |
       579 |             EQ -> Name User (showt 'EQ) (getKey ordEQDataConKey) wiredInSrcSpan
           |                                          ^^^^^^^^^^^^^^^^^^^^^^
        
       /home/curators/work/unpack-dir/unpacked/clash-lib-1.8.1-03ec2cb411fe7ac811914edffea21995ffd0d5c5b6898264fc548c766d146ecb/src/
Clash/Core/Type.hs:580:42: error: [GHC-83865]
           • Couldn't match type ‘GHC.Word.Word64’ with ‘Int’
             Expected: Clash.Unique.Unique
               Actual: GHC.Word.Word64
           • In the third argument of ‘Name’, namely
               ‘(getKey ordGTDataConKey)’
             In the expression:
               Name User (showt 'GT) (getKey ordGTDataConKey) wiredInSrcSpan
:
:
```

Not sure what changed

**Comment by leonschoorl** [comment]
The widening of the GHC uniques got [backported to GHC-9.8.4](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/13624).

We already handle this [for GHC-9.10](https://github.com/clash-lang/clash-compiler/commit/1f8e7658b0c50ac682b425b4b4d7b8ef8c80d722#diff-4bcf3059871a130741e98422e240775122d1b38a4edd3952c92b5f977f296d58R37-R43), but [not in a way that's safe on 32bit systems](https://github.com/clash-lang/clash-compiler/blob/8a827e1e232b795a92da584c3e9cd51a46315680/changelog/2024-07-26T07_36_58%2B02_00_ghc_910_upgrade)

**Comment by christiaanb** [comment]
We've released [v1.8.2](https://github.com/clash-lang/clash-compiler/releases/tag/v1.8.2), which includes a fix for this issue.
