### PR TITLE
Allow compilation on GHC 9.6.7

### LINKED ISSUE #2916: Clash doesn't build on GHC 9.6.7 (but does on 9.6.6)
I get:

```
src/Clash/Unique.hs:73:17: error: [GHC-83865]
    • Couldn't match type ‘Word64’ with ‘Int’
      Expected: GHC.Unique -> Unique
        Actual: GHC.Unique -> Word64
    • In the expression: GHC.getKey
      In an equation for ‘fromGhcUnique’: fromGhcUnique = GHC.getKey
   |
73 | fromGhcUnique = GHC.getKey
   |                 ^^^^^^^^^^
```

Perhaps:

```diff
diff --git a/clash-lib/src/Clash/Unique.hs b/clash-lib/src/Clash/Unique.hs
index 407b9ff64..551f3a48e 100644
--- a/clash-lib/src/Clash/Unique.hs
+++ b/clash-lib/src/Clash/Unique.hs
@@ -17,8 +17,18 @@ module Clash.Unique
   , fromGhcUnique
   ) where
 
-import Data.Word (Word64)
 #if MIN_VERSION_ghc(9,8,4)
+#define UNIQUE_IS_WORD64
+#endif
+
+#if MIN_VERSION_ghc(9,6,7)
+#if !MIN_VERSION_ghc(9,8,0)
+#define UNIQUE_IS_WORD64
+#endif
+#endif
+
+import Data.Word (Word64)
+#ifdef UNIQUE_IS_WORD64
 import GHC.Word (Word64(W64#))
 import GHC.Exts (Word64#)
 #else
@@ -31,7 +41,7 @@ import qualified GHC.Types.Unique as GHC
 import qualified Unique as GHC
 #endif
 
-#if MIN_VERSION_ghc(9,8,4)
+#ifdef UNIQUE_IS_WORD64
 type Unique = Word64
 type Unique# = Word64#
 
@@ -63,7 +73,7 @@ instance Uniquable Unique where
   getUnique = id
   setUnique = flip const
 
-#if !MIN_VERSION_ghc(9,8,4)
+#ifndef UNIQUE_IS_WORD64
 instance Uniquable Word64 where
   getUnique = fromIntegral
   setUnique _ = fromIntegral
```

### PR DESCRIPTION
**Pull request by martijnbastiaan**
Fixes #2916

```
martijn@gammelke:~/code/clash-compiler$ cabal build all -w ghc-9.6.6
Resolving dependencies...
Up to date
martijn@gammelke:~/code/clash-compiler$ cabal build all -w ghc-9.6.7
Resolving dependencies...
Up to date
```

## Still TODO:

  - [X] Write a changelog entry (see changelog/README.md)
  - [X] ~~Check copyright notices are up to date in edited files~~
  - [x] Bump docker images to contain 9.6.7

### CODE REVIEW

File: changelog/2025-04-02T09_08_44+02_00_add_ghc967_support [hunk 1]
```diff
@@ -0,0 +1 @@
+FIXED: Clash doesn't build on GHC 9.6.7 (but does on 9.6.6) [#2916](https://github.com/clash-lang/clash-compiler/issues/2916)
```
Comment (DigitalBrains1) [inline changelog/2025-04-02T09_08_44+02_00_add_ghc967_support:1]:
```suggestion
FIXED: Clash did not build on GHC 9.6.7 (but did on 9.6.6) [#2916](https://github.com/clash-lang/clash-compiler/issues/2916)
```

This is a suggestion; the shape of "fixed" entries in the Changelog that I prefer is "Clash now does X", where X is the right thing. Describing the situation as it was, I'd pick a past tense. When it's in present tense, there's a risk people read "Clash has been fixed to no longer build on GHC 9.6.7" although that seems like a silly change.

Feel free to ignore this suggestion.

File: clash-lib-hedgehog/src/Clash/Hedgehog/Unique.hs [hunk 2]
```diff
@@ -18,6 +18,16 @@ module Clash.Hedgehog.Unique
...
 
+#if MIN_VERSION_ghc(9,8,4)
+#define UNIQUE_IS_WORD64
+#endif
+
+#if MIN_VERSION_ghc(9,6,7)
+#if !MIN_VERSION_ghc(9,8,0)
+#define UNIQUE_IS_WORD64
+#endif
+#endif
```
Comment (martijnbastiaan) [inline clash-lib-hedgehog/src/Clash/Hedgehog/Unique.hs:29]: Can this be deduplicated?

**Review by DigitalBrains1 — APPROVED** [review]

File: changelog/2025-04-02T09_08_44+02_00_add_ghc967_support (hunk 1 above)
Comment (martijnbastiaan) [reply changelog/2025-04-02T09_08_44+02_00_add_ghc967_support]: I'll squash merge :)

File: clash-lib-hedgehog/src/Clash/Hedgehog/Unique.hs (hunk 2 above)
Comment (DigitalBrains1) [reply clash-lib-hedgehog/src/Clash/Hedgehog/Unique.hs:29]:
```haskell
#if MIN_VERSION_ghc(9,8,4) || (MIN_VERSION_ghc(9,6,7) && !MIN_VERSION_ghc(9,8,0))
#define UNIQUE_IS_WORD64
#endif
```

I think. The preprocessor language can do C integer arithmetic,

Comment (martijnbastiaan) [reply clash-lib-hedgehog/src/Clash/Hedgehog/Unique.hs:29]: I thought I tried that, I'll try again

Comment (DigitalBrains1) [reply clash-lib-hedgehog/src/Clash/Hedgehog/Unique.hs:29]: If I feed this to GCC:
```c
#if A || (B && !C)
Yes
#else
No
#endif
```

it correctly obeys the booleans when preprocessing.
