### ISSUE TITLE
Clash doesn't build on GHC 9.6.7 (but does on 9.6.6)

### ISSUE THREAD

**Issue by martijnbastiaan** [clash-lang/clash-compiler#2916]
I get:

```
src/Clash/Unique.hs:73:17: error: [GHC-83865]
    • Couldn't match type ‘Word64’ with ‘Int’
      Expected: GHC.Unique -> Unique
        Actual: GHC.Unique -> Word64
    • In the expression: GHC.getKey
      In an equation for ‘fromGhcUnique’: fromGhcUnique = GHC.getKey
   |
73 | fromGhcUnique = GHC.getKey
   |                 ^^^^^^^^^^
```

Perhaps:

```diff
diff --git a/clash-lib/src/Clash/Unique.hs b/clash-lib/src/Clash/Unique.hs
index 407b9ff64..551f3a48e 100644
--- a/clash-lib/src/Clash/Unique.hs
+++ b/clash-lib/src/Clash/Unique.hs
@@ -17,8 +17,18 @@ module Clash.Unique
   , fromGhcUnique
   ) where
 
-import Data.Word (Word64)
 #if MIN_VERSION_ghc(9,8,4)
+#define UNIQUE_IS_WORD64
+#endif
+
+#if MIN_VERSION_ghc(9,6,7)
+#if !MIN_VERSION_ghc(9,8,0)
+#define UNIQUE_IS_WORD64
+#endif
+#endif
+
+import Data.Word (Word64)
+#ifdef UNIQUE_IS_WORD64
 import GHC.Word (Word64(W64#))
 import GHC.Exts (Word64#)
 #else
@@ -31,7 +41,7 @@ import qualified GHC.Types.Unique as GHC
 import qualified Unique as GHC
 #endif
 
-#if MIN_VERSION_ghc(9,8,4)
+#ifdef UNIQUE_IS_WORD64
 type Unique = Word64
 type Unique# = Word64#
 
@@ -63,7 +73,7 @@ instance Uniquable Unique where
   getUnique = id
   setUnique = flip const
 
-#if !MIN_VERSION_ghc(9,8,4)
+#ifndef UNIQUE_IS_WORD64
 instance Uniquable Word64 where
   getUnique = fromIntegral
   setUnique _ = fromIntegral
```

**Comment by DigitalBrains1** [comment]
We've released [v1.8.3](https://github.com/clash-lang/clash-compiler/releases/tag/v1.8.3), which includes a fix for this issue.
